### ISSUE TITLE
Numerous MALOC errors in Zowe log

### ISSUE THREAD

**Issue by kiril-ibm** [zowe/zowe-install-packaging#927] opened 2019-12-13 16:38 UTC
Just check the Zowe log after start

For plugin=org.zowe.configjs, found 0 data service(s)
MALLOC failed, got NULL for size 0 at site DataServices
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
For plugin=org.zowe.terminal.proxy, found 0 data service(s)
MALLOC failed, got NULL for size 0 at site DataServices
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
For plugin=org.zowe.terminal.tn3270, found 1 data service(s)
added identifier for org.zowe.terminal.tn3270/statediscovery
lookup count=1 name=zosDiscoveryServiceInstaller
Service=org.zowe.terminal.tn3270/statediscovery initializer set internal method=0xEA10C54
initalizeWebPlugin begin, count=1
zosDiscoveryServiceInstaller begin
installing service org.zowe.terminal.tn3270/statediscovery at URI /ZLUX/plugins/org.zowe.terminal.tn3270/services/statediscovery/**
zosDiscoveryServiceInstaller end
initalizeWebPlugin end
For plugin=org.zowe.terminal.vt, found 0 data service(s)
MALLOC failed, got NULL for size 0 at site DataServices
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
For plugin=org.zowe.zlux.auth.zosmf, found 0 data service(s)
MALLOC failed, got NULL for size 0 at site DataServices
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
For plugin=org.zowe.zlux.bootstrap, found 0 data service(s)
MALLOC failed, got NULL for size 0 at site DataServices
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
For plugin=org.zowe.zlux.ng2desktop, found 0 data service(s)
MALLOC failed, got NULL for size 0 at site DataServices
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
For plugin=org.zowe.zlux.proxy.zosmf, found 0 data service(s)
MALLOC failed, got NULL for size 0 at site DataServices
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
For plugin=org.zowe.zlux.sample.angular, found 0 data service(s)
MALLOC failed, got NULL for size 0 at site DataServices
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
For plugin=org.zowe.zlux.sample.iframe, found 0 data service(s)
MALLOC failed, got NULL for size 0 at site DataServices
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
For plugin=org.zowe.zlux.sample.react, found 0 data service(s)
MALLOC failed, got NULL for size 0 at site DataServices
initalizeWebPlugin begin, count=0
initalizeWebPlugin end
For plugin=org.zowe.zosmf.workflows, found 0 data service(s)
MALLOC failed, got NULL for size 0 at site DataServices
initalizeWebPlugin begin, count=0
initalizeWebPlugin end

**Comment by 1000TurquoisePogs** [comment] 2020-01-22 20:45
Closing this as a duplicate of https://github.com/zowe/zss/issues/140
Still needs to be addressed.

**Closed by 1000TurquoisePogs** 2020-01-22 20:45 UTC
