### ISSUE TITLE
Migrate smpe-packaging to zowe-install-packaging

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-install-packaging#719] opened 2019-09-13 08:35 UTC
As part of CUPIDs work, there is a new installation test suite that should be merged into the zowe-install-packaging and zowe-install-test repositories.

**Comment by jackjia-ibm** [comment] 2019-09-13 20:05
Duplicate of #551

**Closed** 2019-09-20 12:01 UTC
Labels: CI/CD
