### ISSUE TITLE
Permission denied when ~/.zowe_profile does not exist on first install

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#353] opened 2019-02-05 21:51 UTC
```
IBMUSER:/SYSTEM/var/zowe/0.9.2/zowe-1.0.0/install>./zowe-install.sh
---------------------------------------------------------------------
touch: file "/u/ibmuser/.zowe_profile": EDC5111I Permission denied
```

**Comment by Joe-Winchester** [comment] 2019-02-05 22:04
@hogstrom - unable to re-create.  I tried this with no .zowe_profile and a clean shell.  What permission do you have on your .zowe_profile ?  The install script creates it so I'm unsure why it wouldn't be able to touch it

**Comment by MarkAckert** [comment] 2019-02-27 21:19
@Joe-Winchester 
I've had a similar error when the full directory path was not available on my system.
For example: `touch /u/users/markusr/zowe/.zowe_profile` will fail  with EDC5129I No such file or directory if only `/u/users/markusr/` exists (`zowe` directory does not). I think the command output of `touch` was sufficient for me to debug and fix the environment, but we could perform some additional validation of users home directory. Thoughts?

**Comment by Joe-Winchester** [comment] 2019-02-28 10:54
@MarkAckert - We don't create .zowe_profile in /zowe, it's only expected to be in ~.  The code that creates this is in zowe-init.sh and is
``` touch ~/.zowe_profile     # ensure it exists
# 2. set those variables (if any) in Zowe install environment
. ~/.zowe_profile 
```
I know we have another problem where if the installer is putting into ~/zowe/1.0.0 and has to create /zowe/ then it doesn't put -x permission on this which makes Zowe's STC unable to start as it can't read the directory.  We have a separate issue #201  for this, and I have thought about how to fix this.  We'd need to parse the folder path we're creating and then after the first pax command that creates the folder recurse along and do a chmod o+x, or else we could see if some kind of umkask works to get permissions set correctly.
However, I don't think that this git issue is still existing based on looking at the current code, although I know that #201 does need fixing at some point.

**Comment by MarkAckert** [comment] 2019-02-28 15:14
Thanks Joe, and I know my directory was not a 1-1 example - the home directory on one of our systems is far down the directory hierarchy and had missing intermediate directories due to missing zFS mounts - just wanted to convey that missing intermediate directories can happen.  I'll close this issue and take a look at #201.

**Comment by MarkAckert** [comment] 2019-02-28 15:15
Closing as the issue is uncommon and existing output error appears sufficient to investigate/remediate.

**Closed by MarkAckert** 2019-02-28 15:16 UTC
Labels: bug, install
