### ISSUE TITLE
Some processes can't stop during zowe server shutting down

### ISSUE THREAD

**Issue by rjmaomao** [zowe/zowe-install-packaging#1836] opened 2020-12-10 09:03 UTC
Hello,

I'm not sure if this is the correct place to report the issue. Please let me know if I should open it against other repo. 

I run zowe server with started task configured. I usually start zowe by MVS command S ZOWESVR, and stop it by C ZOWESVR. After issuing S ZOWESVR I can see there are around 20 processes created( can be viewed from SDSF S.DA or S.PS), when stop the server after issuing command C ZOWESVR, there were some processes can’t stop successfully, such as ZOWESV28, ZOWESV29.   I remember I have seen all processes stoped once C ZOWESVR was issued. Not sure why those processes can’t be stopped now. I had to use MVS command such as C ZOWESVR8,A=xxx to cancel these processes manually one by one.  The process that can't stop are from java code as below. I saw this same issue on different versions, including 1.11, 1.15, 1.17 

```
ZOWESV29  OTHER KERNEL WAIT  java -Xms16m -Xmx512m -Dibm.serversocket    
ZOWESV28  OTHER KERNEL WAIT  java -Xms16m -Xmx512m -Xquickstart -Dibm    
ZOWESV28  OTHER KERNEL WAIT  java -Xms16m -Xmx512m -Dibm.serversocket    
ZOWESV29  OTHER KERNEL WAIT  java -Xms32m -Xmx256m -Xquickstart -Dibm   
```
 
Is there any suggestion on why is this happening and how to prevent it? Thanks!

**Comment by Joe-Winchester** [comment] 2020-12-10 11:29
@jandadav - have you seen anything like this where the APIML springboot servers don't terminate correctly ?  @jackjia-ibm - I think this might be something that the Zowe launcher will address, but it'd be good to get to the bottom of why the process remain even when the STC is cancelled.

**Comment by stevenhorsman** [comment] 2020-12-14 10:47
This looks like a duplicate of #1759

**Closed by stevenhorsman** 2020-12-14 10:47 UTC
