### ISSUE TITLE
Bad behavior on zowe install script

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe-install-packaging#98] opened 2018-10-03 21:37 UTC
I tried to install zowe with my mainframe environment, but the install script didn't play well with my shell settings.
I have a .profile file which runs the shell of my preference at the end (runs bash). It seems that the install script is trying to read through and execute contents of .profile to gain env vars that would help it to complete, but the result was bad: the script died quickly as it accidentally spawned bash, which was now also stealing stdout and stderr, so my original shell was toast... anything I'd type would execute but be lost. 'ls' would not show any files existing, for example.

I know Zowe is intended to be run as its own user, but there can be a variety of things in .profile, so I think it is not safe to be re-reading, and later, adding to it.

**Comment by Joe-Winchester** [comment] 2018-11-19 12:09
@John-A-Davies - is there a way to detect from the script whether it's inside bash and if so exit bash, and if it's not inside bash to just carry on ?  This is where the problem is really coming from, and being able to execute the .profile seems like a good thing to get the environment variables picked up but Sean's point is a good one that if his script runs bash then it borks the installer.

**Comment by patbossman** [comment] 2018-11-27 01:59
FYI - I also saw this behavior.  In my case, the installer put a long dashed line and then the bash prompt, and it didn't feel like it was running the installer at all.  When I type "exit", then it runs the installer, seemingly successfully.

**Comment by John-A-Davies** [comment] 2018-11-30 15:49
The profile is dealt with in `zowe-init.sh` ... looking into it.

**Comment by John-A-Davies** [comment] 2019-01-10 11:03
The file ~/.profile is executed by bash for login shells. This file is not read by bash, if ~/.bash_profile or ~/.bash_login exists, so us adding lines to ~/.profile might have no effect.  So I wonder if we will have to cater for Bash users, plus Korn users, etc?

**Comment by John-A-Davies** [comment] 2019-01-10 15:16
@1000TurquoisePogs @patbossman Can you please attach your USS .profile or other script that runs when you log in?   I'd like to use them as test cases for our solution.  Please also include the OMVS RACF setting for PROGRAM for your TSO userid (it's usually /bin/sh) and also include the value of shell env variable SHELL.

**Comment by John-A-Davies** [comment] 2019-01-10 16:02
So there are 2 problems in zowe-init.sh

1. (line 48) executing the .profile by using the dot command runs all of it, including any ~/.bashrc or shell startup command that might be inside it.  All we need to do instead is run its commands that set env vars.  

2. (line 178) appending a new `export` command to .profile could mean that it comes after a command to invoke a shell e.g. Bash.  We'd need to insert that `export` command earlier in the file, but not before the first line, if that says `#!/bin/shellname` or similar.

**Comment by John-A-Davies** [comment] 2019-01-14 09:44
Fixed by #240.

**Closed by John-A-Davies** 2019-01-14 09:44 UTC
Labels: bug, in progress
