### ISSUE TITLE
Ansible playbook needs an update for installing a PTF package on an SMPE/PTF zowe  system 

### ISSUE THREAD

**Issue by raymondyanli** [zowe/zowe-install-packaging#1791] opened 2020-11-13 18:18 UTC
*Customer content*

**Is your feature request related to a problem? Please describe.**
When running install-ptf.yml to install PTF package on a SMPE/PTF already installed system, installation fails as it complains "AZWE001 IS NOT IN THE GLOBAL ZONE" in ACCEPT stage.

**Describe the solution you'd like**
Be able to install any PTF package on a system which a SMPE/PTF package already installed.

**Describe alternatives you've considered**

**Additional context**

Z3RECEIV fails because PTFs are already received. (Re-Applying PTFs doesn't require this step), This step needs to be done once for the first time you apply the new PTFs.
Z2ACCEPT fails FMID AZWE001 doesn't exist in GLOBAL Zone.

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by jackjia-ibm** [comment] 2020-11-18 16:26
More details related to this issue:

**Purpose**

Re-applying a PTF even though it's already applied in the past. This will clear the blocking issue for Yan's team to apply nightly PTF without cleanup and re-installing FMID.

**Issues We See**

With current pipeline, PTF installation will always run `Z2ACCEPT` and `Z3RECEIV` steps. This will fail if the PTF has already been applied.

**Solution**

To solve the issue, we need to check if the PTF has been applied by querying SMPE CSI `zowe_smpe_hlq_csi` and then based on the status:

- if it's already been applied, we need to skip `Z2ACCEPT` and `Z3RECEIV` steps. We already have `REDO` defined for `Z4APPLY` step. So the same PTF will be updated.
- if it's not yet been applied, we continue on as usually to run all PTF installation steps.

I remember in the past to use JCL to query what PTF have been applied in CSI. @NayerNajafi will be the best person to fill in the details here. If JCL is the best way, the playbook task will need to wait for the JCL job to be finished, read job log and find out if current PTF number is in the list.

Please let me know if there are any questions. Thanks all.

**Comment by NayerNajafi** [comment] 2020-11-18 18:15
@jackjia-ibm You're right, we can use SMP/E LIST command to 
1- check the SYSMODs that have been applied:

```
//LIST     EXEC PGM=GIMSMP                     
//SMPCSI   DD DISP=SHR,DSN=Zowe-csi-dataset
//SMPPTFIN DD DUMMY                            
//SMPHOLD  DD DUMMY                            
//SMPLOG   DD DUMMY                            
//SMPOUT   DD SYSOUT=*                         
//SMPRPT   DD SYSOUT=*                         
//SMPLIST  DD SYSOUT=*                         
//SMPCNTL  DD  *                               
SET      BDY(target-zone)     .                      
LIST     SYSMOD                                
         FORFMID(AZWE001) .                    
//*                                            
```
2- Check the SYSMODs that have been applied, but that have not been accepted in the related zone:

```
//LIST     EXEC PGM=GIMSMP                       
//SMPCSI   DD DISP=SHR,DSN=Zowe-csi-dataset  
//SMPPTFIN DD DUMMY                              
//SMPHOLD  DD DUMMY                              
//SMPLOG   DD DUMMY                              
//SMPOUT   DD SYSOUT=*                           
//SMPRPT   DD SYSOUT=*                           
//SMPLIST  DD SYSOUT=*                           
//SMPCNTL  DD  *                                 
SET      BDY(target-zone)     .                        
LIST     SYSMOD                                  
         NOACCEPT                                
         FORFMID(AZWE001) .                      
//* 
```

**Comment by stevenhorsman** [comment] 2020-11-19 14:32
@raymondyanli @NayerNajafi  - based on what Kathy mentioned in the extender call I need a bit of clarification of what is asked for.
Kathy said that you wanted the test the more realistic user scenario (which is totally fair) that a customer installed FMID, the ptf v.n then ptf v.n+1. In that case I don't quite understand what the problem is with the currently playbook as just running install-ptf for 2 different PTF numbers should work?
Alternatively if you are asking to update PTF v.n (yesterday's build) with v.n (today's build) - then I'm not sure how that works where we check that it's already been accepted and received as the PTF number is the same for both of them, so by scanning the SYSMODs I don't think I can tell the difference and if we just redo the APPLY that would just re-install yesterday's build?

**Comment by raymondyanli** [comment] 2020-11-19 21:29
@stevenhorsman 
As you commented above, basically, we’d like to have two scenarios for installing SMPE-PTF package:
1. Install FMID + PTF v.n 
that is what we are currently doing in our pipeline. pipeline will first uninstall zowe, then install fmd and ptf n.v, separately. 

2. Install PTF n.v alone (customer scenario) 
on top of whatever the zowe(smid+ptf) there, pipeline will not uninstall zowe, instead, install ptf n.v (or ptf n.v+1) directly

I have tried running the install-ptf.yml on a zowe which a smid+ptf package already installed, it failed with error message: “AZWE001 IS NOT IN THE GLOBAL ZONE“ ….

@NayerNajafi  looked into this scenario and came up:
  
Z0PTFUCL is OK
Z1ALLOC is OK

Z3RECEIV fails because PTFs are already received. (Re-Applying PTFs doesn't require this step), This step needs to be done once for the first time you apply the new PTFs.
GIM38601E ** SYSMOD UO01958 WAS NOT RECEIVED BECAUSE IT HAS ALREADY BEEN RECEIVEVED BECAUSE IT HAS ALREADY BEEN RECEIVED.
GIM38601E ** SYSMOD UO01959 WAS NOT RECEIVED BECAUSE IT HAS ALREADY BEEN RECEIVEVED BECAUSE IT HAS ALREADY BEEN RECEIVED.

Z2ACCEPT fails because you are trying to accept the SYSMODE (FMID AZWE001) that doesn't exist in GLOBAL Zone. I would say this part is not required for Re-Applying PTFs as well. You did/ran this job while installing SMP/E FMID for the first time.
                                                   
That is what this issue about to see if ansible playbook(install-ptf.yum) can do somethings, like detecting if a PTF exists or not, then bypassing certain stages or run full stages for installing the ptf n.v.x. I am not sure if that is doable...

**Comment by jackjia-ibm** [comment] 2021-02-17 22:29
@raymondyanli this fix has been merged. The `install-ptf.yml` playbook should allow you to install same PTF number again. Please let me know if it works or not. Thanks.

**Closed** 2021-04-15 18:16 UTC
Labels: enhancement
