### ISSUE TITLE
Allow auto-configuration of ZLUX behind the mediation layer

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#612] opened 2019-08-29 21:05 UTC
ZLUX can run behind the mediation layer which is documented with manual steps in

https://www.zowe.org/docs-site/latest/user-guide/mvd-configuration.html#configuring-the-framework-as-a-mediation-layer-client

This could be moved to be automated during the configuration/launch of Zowe

**Comment by stevenhorsman** [comment] 2019-09-09 12:52
@Joe-Winchester - what is the difference between this and #589?

**Comment by 1000TurquoisePogs** [comment] 2019-10-17 22:13
Probably should close one? Doing this for now.

**Comment by 1000TurquoisePogs** [comment] 2019-10-17 22:14
I think my enhancement to allow templates & -D args for altering any config attribute will make this easier to drive, so assigning me to this item in that regard.

**Comment by stevenhorsman** [comment] 2020-01-23 12:19
Hey @1000TurquoisePogs, we're having problems when running zlux through the gateway - the tn3270 and vt terminal apps get 404s when they talk through the gateway port and we can't open USS files in the editor. Is there something we are missing, or do we have a configuration issue?

**Comment by 1000TurquoisePogs** [comment] 2020-03-20 23:32
I did notice the editor didnt work behind the gateway, which was something we figured out and fixed. https://github.com/zowe/zlux-app-manager/pull/187 
But, I'm not sure why the terminals are doing that. @NakulManchanda seems to have the issue on only one browser for example.

**Comment by stevenhorsman** [comment] 2020-05-06 13:18
I think we can close this - the issue that Joe and I saw was the same as the issue with symbolic links. I'm not sure why it wasn't showing up when we didn't go through the gateway, but I can't reproduce now.

**Closed by stevenhorsman** 2020-05-06 13:18 UTC
Labels: Cupids, LTSR
