### ISSUE TITLE
S ZOWESVR fails with syntax error on script line 1

### ISSUE THREAD

**Issue by patbossman** [zowe/zowe-install-packaging#142] opened 2018-11-19 21:19 UTC
Here is the error from the output:
run-zowe.sh 1: FSUM7332 syntax error: got (, expecting Newline

Burned a lot of time, but finally tracked this down.  I had set some default encoding variables:
_ENCODE_FILE_EXISTING=UNTAGGED
_ENCODE_FILE_NEW=ISO8859-1

This was causing my run-zowe.sh to be tagged with:  t ISO8859-1   T=on

I tracked down the original run-zowe.sh from the install directory, and all the *.sh files were untagged.  When I copied it over and set the environment variable, the ZOWESVR proc worked properly.

I think these environment variables need to be unset when the install is run or some of the scripts get messed up.

**Comment by Joe-Winchester** [comment] 2018-11-20 11:38
Problem:
The .sh scripts in the /scripts are not all being tagged as IBM-1047. 

Solution:
in zowe-prepare-runtime.sh do a chtag -t -c IBM-1047 for the files
/scripts/zowe-runtimeauthorize.sh
/scripts/zowe-start.sh
/scripts/zowe-stop.sh
/scripts/internal/opercmd
/scripts/internal/run-zowe.sh

**Comment by patbossman** [comment] 2018-11-20 13:48
I'm not sure what copies the ZOWESVR.jcl into the PROCLIB, but that script used to produce an empty file for me, and now it populates correctly also.

**Comment by John-A-Davies** [comment] 2018-11-21 13:53
I'd like to know more about _ENCODE_FILE_NEW=ISO8859-1 ...
I've not seen the doc for _ENCODE_FILE_* variables in USS.  @patbossman can you send me a link, please?

**Comment by patbossman** [comment] 2018-11-26 17:34
I've only seen this in the Rocket port of bash, the README.ZOS
https://my.rocketsoftware.com/RocketCommunity#/downloads

Then find bash, and when you follow the downloads, you will see README.ZOS.

**Comment by jshewbert** [comment] 2018-12-10 22:46
I'm running into the same issue and it appears that all of my *.sh files are tagged ISO8859-1.

I can copy the *.sh files mentioned above from the /install/scripts directory but I also see these syntax errors for some api-mediation scripts that I cannot locate in the /install directory.

**Comment by patbossman** [comment] 2018-12-13 13:30
Props to Jørn from Rocket, he put the autocvt stuff into the proc, which also works.  
//ZOWESTEP EXEC PGM=BPXBATSL,REGION=0M,TIME=NOLIMIT,
//  PARM='PGM /bin/sh &SRVRPATH/../scripts/internal/run-zowe.sh'
//STDOUT   DD SYSOUT=*
//STDERR   DD SYSOUT=*
//STDENV   DD *
_BPXK_AUTOCVT=ON
_CEE_RUNOPTS=FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)
NODE_HOME=/proj/cqmdata/data33/zowe/node-v6.14.3-os390-s390x
PATH=/bin:$NODE_HOME/bin:$PATH:.

**Comment by patbossman** [comment] 2018-12-13 13:39
Here's a more complete:
//STDENV   DD *
_BPXK_AUTOCVT=ON
_CEE_RUNOPTS=FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)
_TAG_REDIR_IN=txt
_TAG_REDIR_OUT=txt
_TAG_REDIR_ERR=txt

(node home is in the script file)

**Comment by John-A-Davies** [comment] 2019-01-16 14:37
This is pending a review of our `chtag` policy for all files we install.   Currently we don't run `chtag`.

**Comment by stevenhorsman** [comment] 2019-01-29 10:15
Moved to post-1.0 as we don't have time to do a proper investigation now

**Comment by John-A-Davies** [comment] 2019-01-30 14:43
Here's how I think it works.  

Text files have to be in the right encoding for apps (like java or C programs) that don't honour tags.

They have to be tagged for those that do (like sed, cat, vi, and others that perform I/O on text files), and auto-convert needs to be enabled (globally in OMVS with AUTOCVT=ALL or ON, or for a single user by env var _BPXK_AUTOCVT=ON, and other such settings as noted by other posters.  

The FILETAG(AUTOCVT ... only takes effect if  the _BPXK_AUTOCVT environment variable value is set to ON or the _BPXK_AUTOCVT environment variable is unset and AUTOCVT(ON) was specified in the active BPXPRMxx member on your system.

I tried this in an experiment.

I looked at file

`api-mediation/api-defs/datasets.yml`

it's encoded in ASCII, and ISPF 3.17 shows correct contents when you use VA.  While I was there, I changed its MF tags to 
```
CCSID 819
Auto-convert yes
```
So it looks like this on USS:
```
api-mediation:>ls -lT api-defs/datasets.yml
t ISO8859-1   T=on  -rwxrwxrwx   1 WINCHJ   TSOUSER     1106 Jan 25 15:04 api-defs/datasets.yml
```
Now if I use USS to read the file with 'vi' or 'cat' etc, it shows correctly, but only if I have 

`_BPXK_AUTOCVT=ON`

AUTOCVT was not specified in the active BPXPRMxx member, so it defaulted to OFF.

**Comment by John-A-Davies** [comment] 2019-01-30 17:00
FYI, the ukgiza1 zD&T system has this in its `/etc/profile` 
```export _BPXK_AUTOCVT=ON
export _CEE_RUNOPTS="FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
export _TAG_REDIR_ERR=txt
export _TAG_REDIR_IN=txt
export _TAG_REDIR_OUT=txt
```

**Comment by likepunk** [comment] 2019-01-30 18:48
This is good information,  thank you John. 

however,  in my environment, although I have AUTOCVT  is  turned  on, my api-defs are not  readable while  it  is  encoded/tagged with IBM-1047.

does  the installation  always have  to be done by IZUSVR? or  can it be  installed by a user  who has access/in a same group then  do chgrp on  all directories?

:YKIM:/u/ykim:Ready set |grep  AUTO
_BPXK_AUTOCVT="OFF"
_CEE_RUNOPTS="FILETAG(AUTOCVT,AUTOTAG) POSIX(ON) ALL31(ON)"
:YKIM:/u/ykim:Ready 
:YKIM:/u/ykim:Ready ls  -altrT /zoe/zowe-runtime/api-mediation/api-defs
total 72
                    drwxrwxr-x   6 BPXROOT  IZUADMIN    8192 Jan 30 11:24 ..
t IBM-1047    T=on  -rwxrwxrwx   1 BPXROOT  IZUADMIN     960 Jan 30 11:25 zosmf.yml
t IBM-1047    T=on  -rwxrwxrwx   1 BPXROOT  IZUADMIN    1097 Jan 30 11:25 datasets.yml
t IBM-1047    T=on  -rwxrwxrwx   1 BPXROOT  IZUADMIN     706 Jan 30 11:25 zos.yml
t IBM-1047    T=on  -rwxrwxrwx   1 BPXROOT  IZUADMIN     311 Jan 30 11:25 uss.yml
t IBM-1047    T=on  -rwxrwxrwx   1 BPXROOT  IZUADMIN     882 Jan 30 11:25 jobs.yml
                    drwxrwxrwx   2 BPXROOT  IZUADMIN    8192 Jan 30 11:25 .
:YKIM:/u/ykim:Ready cat /zoe/zowe-runtime/api-mediation/api-defs/zos.yml
?????????˚?????????????????:?ˎ?????????%?????(?:|?_????%%/>???ˎ????????????????>????(?:|?(????%%/>???ˀ???耠&????????????????/?/%??????%?????:?ˎ???????>??/>???/????%˚??????????????˚?&???>??>????%????_??????????_?&/????%/??????%???????_???/????ˀ/Ȁ?????/_????<????????????????????˚???????????/???/`??%??/??Α????$/??????)?#_/?????????>'????????????????????%/??????%??/??Α:?ˎ??????/???>?????????????/????????_??_:?ˎ???????????/???/`??%??/??Α?????????????????>????????????????????_?>?/???>??%??????˚?&???>??>????%????_???_/?????%??????/?/%??????%?˚?????:?˚????????????%???:|?(????%%/>???ˀ???????ˎ??????????????????>????(?:|?(????%%/>???ˀ???????????ˎ:YKIM:/u/ykim:Ready

**Comment by likepunk** [comment] 2019-01-31 02:57
Sorry, I realized  above  capture  had  BPXK_AUTOCVT="OFF", but  after changing  /etc/profile to  enable  it, I still  get invalid  characters on api-defs/*.yml files.

My question  is, would this  character  set /encoding   needs to be  changed to  ISO-8859-1 after installation?

the current working directory: /u/ykim is at 3% capacity
:YKIM:/u/ykim:Ready set  |grep  AUTO
_BPXK_AUTOCVT="ON"
_CEE_RUNOPTS="FILETAG(AUTOCVT,AUTOTAG) POSIX(ON) ALL31(ON)"
:YKIM:/u/ykim:Ready bash
RPRT:YKIM:/u/ykim:Ready cd  /RPRT/zoe/zowe-runtime/api-mediation/api-defs/
RPRT:YKIM:/RPRT/zoe/zowe-runtime/api-mediation/api-defs:Ready ls  -T
t IBM-1047    T=on  datasets.yml
t IBM-1047    T=on  jobs.yml
t IBM-1047    T=on  uss.yml
t IBM-1047    T=on  zos.yml
t IBM-1047    T=on  zosmf.yml
RPRT:YKIM:/RPRT/zoe/zowe-runtime/api-mediation/api-defs:Ready cat uss.yml
?????????˚??????????????????%??????ˎ???????%?????(??>?̀?`???_????????ˎ??????????????>????(?:|??>?̀?`???_????????ˀ?񎀀???>??/>???/????%˚????????????˚?&???>??>????%????_????????????_?&/????%/???

**Comment by John-A-Davies** [comment] 2019-01-31 10:35
The api-defs/*.yml files **must** be encoded in ASCII ISO8859-1 when the install is complete.  You can check this with ISPF 3.17; view the file, and if it appears as non-text characters, it's not in EBCDIC.  Then view it as ASCII with the 'VA' command; if it appears as valid text, then it's correctly encoded in ASCII.  

Tagging is separate and does not affect the way ISPF 3.17 displays the file.  It does however affect the way shell programs like 'vi' and 'cat' process the file.  If that file is marked with **both** of these
```
CCSID 819
Auto-convert yes
```
and auto-convert is enabled with AUTOCVT at some level, then 'cat' and 'vi' will show the file correctly.

You should not have to convert the file (because it should already be in ASCII), and you should not tag it as CCSID 1047 (because the CCSID refers to the encoding of the source file, not the encoding to which it should be converted).  Conversion, if performed, will be **from** the CCSID you specify, **to** EBCDIC (1047)

**Comment by 1000TurquoisePogs** [comment] 2019-03-05 20:49
Having the same sort of output from the api-mediation/api-defs/*.yml files.
They are tagged:
```
> ls ~/zowe/1.0.1rc2/api-mediation/api-defs/*.yml
t ISO8859-1   T=on  -rwxrwxrwx   1 TSSPG    TSUSER      1639 Mar  5 13:45 /u/tsspg/zowe/1.0.1rc2/api-mediation/api-defs/datasets.yml
t ISO8859-1   T=on  -rwxrwxrwx   1 TSSPG    TSUSER       888 Mar  5 13:45 /u/tsspg/zowe/1.0.1rc2/api-mediation/api-defs/jobs.yml
t ISO8859-1   T=on  -rwxrwxrwx   1 TSSPG    TSUSER       313 Mar  5 13:45 /u/tsspg/zowe/1.0.1rc2/api-mediation/api-defs/uss.yml
t ISO8859-1   T=on  -rwxrwxrwx   1 TSSPG    TSUSER       963 Mar  5 13:45 /u/tsspg/zowe/1.0.1rc2/api-mediation/api-defs/zosmf.yml
```
But when using `cat`, they print out characters that probably can't be copied into this textbox.

No other files in the environment seem to be wrong, as far as I can tell.
In fact, other tagged files are fine:
```
~/zowe/1.0.1rc2/scripts> ls
total 144
                    drwxr-xr-x   2 TSSPG    TSUSER      8192 Mar  5 13:45 internal
t ISO8859-1   T=on  -rwxrwxrwx   1 TSSPG    TSUSER      2482 Mar  5 13:45 zowe-runtime-authorize.sh
t ISO8859-1   T=on  -rwxrwxrwx   1 TSSPG    TSUSER       870 Mar  5 13:45 zowe-start.sh
t ISO8859-1   T=on  -rwxrwxrwx   1 TSSPG    TSUSER       871 Mar  5 13:45 zowe-stop.sh
```

These all `cat` out normally.
Here's some potentially relevant env vars:
```
TERM=xterm
_BPXK_AUTOCVT=ON
LANG=C
_CEE_RUNOPTS=FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)
TERMINFO=/usr/share/lib/terminfo
```

I'm just wondering how the scripts & the yaml files differ in install&packaging, since they're both tagged identically yet yield different output behavior.

**Comment by jordanCain** [comment] 2019-03-05 20:57
@1000TurquoisePogs The api-def files are constructed here: https://github.com/zowe/zowe-install-packaging/blob/master/scripts/zowe-api-mediation-configure.sh#L121 

At the end of the creation we are converting them from IBM-1047 to IBM-850

**Comment by 1000TurquoisePogs** [comment] 2019-03-05 22:27
Thanks, but now the mystery deepens.
If I make a script out of that section you referenced that creates a file inline, and does iconv on it... it works. file1 is 1047, file2 upon tagging as iso8859-1 becomes readable.
But yet the files that came from the installer don't. And, using iconv doesn't make this any better.
Strangely, the contents of the files seem to have nothing in common other than length. Using `od -t x1 FILENAME`, the hex I get back seems unrelated.
Not sure where to go from here, but maybe this helps.

**Comment by John-A-Davies** [comment] 2019-03-06 12:40
On my 1.0.0 systems, which are vanilla installs without me tagging or converting files, I have this:
`api-defs/*.yml` are in ASCII, untagged, conversion=off.
`scripts/*.sh` are in EBCDIC, untagged, conversion=off.

@1000TurquoisePogs if you tag those files and AUTOCVT conversion is active, they will be converted from the stated tagged encoding to EBCDIC, which is probably the wrong thing to do for both `api-defs/*.yml` and `scripts/*.sh`.  Why do you think your files are encoded and tagged differently from mine?

**Comment by 1000TurquoisePogs** [comment] 2019-03-06 17:09
>Why do you think your files are encoded and tagged differently from mine?
So, I tried a few more configurations, and found out that in some cases this is true, in some cases it isn't.
As it turned out, I saw 3 different behaviors in 3 different environment configs

Around the line that jordan pointed out, I printed the tagging and then did a `cat` on both the temp zosmf.yml file, and the post-iconv zosmf.yml file.
1. temp was untagged but cat-able, final was untagged and not cat-able due to assuming EBCDIC when untagged... still recoverable though
2. temp was tagged EBCDIC, final was also tagged EBCDIC... essentially the same thing as 1
3. temp was tagged ISO8859-1, and it really was! final was tagged ISO8859-1

In case 3, because the script unconditionally does iconv assuming the file was EBCDIC, it munges the contents.
I think the solution is just to only do iconv after conditionally checking the tagging.

**Comment by patbossman** [comment] 2019-03-06 19:34
I think we should ensure all scripts are encoded and tagged with precision, and not leave it to whatever z/OS environment settings are.

**Comment by John-A-Davies** [comment] 2019-03-07 12:28
@patbossman Yes.  I think the problem is that user environments have many possible settings which affect the actions of our install + config scripts when they perform `sed` and redirect operations controlled by the Enhanced ASCII settings:
The _BPXK_AUTOCVT variable controls the autoconversion, while the _TAG_REDIR_* variables control the tagging if standard input/output is redirected with <, > or |.
```
export _TAG_REDIR_ERR=txt
export _TAG_REDIR_IN=txt
export _TAG_REDIR_OUT=txt
```
We can't really enforce the presence or absence of these settings in the user's environment.
So one solution to protect ourselves is to unset them all in the environment for the execution of our config script, to enable its config operations to work correctly.  Such unset will have no effect post-config or for any other user.

Also be aware of
`export IBM_JAVA_OPTIONS="-Dfile.encoding=ISO8859-1" `

Further reading - General note about conversion, FYI

Beginning with z/OS Version 1 Release 2, IBM introduced a collection of features known as enhanced ASCII support that are intended to solve these problems. These features include:

- the ability to "tag" a file with the encoding used by that file

- C/C++ compiler support for using ASCII at runtime as a program's internal character encoding

- automatic conversion of data between the encoding in a file and the encoding used internally by a program

- runtime services for manipulating file tags and controlling data conversion support in many commonly-used Unix commands for ASCII data, including respect for file tags and explicit control over data conversion

**Comment by dmitrynikolaev** [comment] 2019-03-07 12:50
@John-A-Davies @1000TurquoisePogs 

Another solution is to use `tee` which doesn't perform auto encoding instead of redirecting output to files.
So instead of `> file` we can do `| tee file > /dev/null`

We've been using this workaround for a while, and it seems to work in all our environments.

**Comment by John-A-Davies** [comment] 2019-03-07 13:19
The   z/OS 2.3.0 z/OS XL C/C++ Programming GuideCoding: Advanced Topics says it affects pipes too:

_BPXK_AUTOCVT
    Activates or deactivates automatic text conversion of tagged UNIX file system files. ...
    ON
        Activates the automatic conversion of tagged files for Enhanced ASCII. This affects conversion for I/O for regular, pipe, and character special files that are tagged.
    ALL
        Activates the automatic conversion of tagged files that are supported by z/OS UNICODE. This affects conversion for I/O for regular and pipe files that are tagged. If the conversion is between EBCDIC and ASCII, it also affects conversion for I/O for character special files.

**Comment by dmitrynikolaev** [comment] 2019-03-07 14:06
Right.
I guess that `tee` itself writes files in EBCDIC unconditionally.
Does this work in your environment?

**Comment by John-A-Davies** [comment] 2019-03-07 14:25
I propose that the install script should nullify all Enhanced ASCII environment variables related to tagging and conversion for the duration of the install, so we don't have to circumvent auto-conversion during file redirection, creation or any other operation yet to be discovered.  Otherwise we spend an open-ended amount of time closing loopholes.  @Joe-Winchester Comments, please?

**Comment by likepunk** [comment] 2019-05-17 20:07
Any latest updates on this yet please?

**Comment by John-A-Davies** [comment] 2019-05-20 08:27
We've not had any further defects raised about this.  
This is pending a review of our chtag policy for all files we install.

**Comment by dan-jast** [comment] 2019-05-21 19:16
Just letting the team know, I installed 1.2.0 this morning and ran into this threads issue. Got the error message `/usr/lpp/zowe/1.2.0/scripts/internal/run-zowe.sh 1: FSUM7332 syntax error: got (, expecting Newline`
Also, just as @patbossman suggested, the `zowe-install.sh` script allocated an empty ZOWESVR proc, which I then had to manually copy from USS myself. 
After performing the following to `run-zowe.sh` I was able to get ZOWESVR PROC to start... with errors:
`ls -laT --- IF shell scripts are in ISO8859-1, then convert to IBM-1047 otherwise skip! ---
mv run-zowe.sh run-zowe.sh~   
iconv -f ISO8859-1 -t IBM-1047 run-zowe.sh~ > run-zowe.sh
chtag -tc IBM-1047 run-zowe.sh`

**Comment by patbossman** [comment] 2019-05-22 16:50
I basically convert all of my .sh to IBM-1047 now.  I can get things to run OK directly in USS, but when I run the scripts via procs, this issue arises and the most reliable solution for me has been to convert and tag to IBM-1047.

**Comment by plavjanik** [comment] 2019-06-12 19:43
We were able to resolve this problem with @dan-jast. To prevent different encoding during the installation, we had to set following environment variable before running the `zowe-install.sh` script:

```bash
export PATH="./:/bin:/usr/sbin:/usr/lpp/NFS:/usr/local/bin:/usr/lpp/java/J1.8/J8.0_64/bin"
export _BPXK_AUTOCVT="OFF"
export _CEE_RUNOPTS=""
export _TAG_REDIR_IN=""
export _TAG_REDIR_OUT=""
export _TAG_REDIR_ERR=""
```

This prevents any automatic conversions and tagging. The z/OS UNIX utilities are used by setting the `PATH`. The ported Rocket utilities work differently with encodings.

To make sure that the Zowe startup scripts will work well no matter what is in the profile, it is necessary to set the same variables in the `$ZOWE_ROOT_DIR/scripts/internal/run-zowe.sh` script.

**Comment by John-A-Davies** [comment] 2019-06-18 08:42
We've left the full review of code page behaviour in the background up to now.  

I agree that exporting the above underscore variables during install, to override the site and user settings, is correct.

Note also that there is a `BPXK_CCSIDS` variable.

Can we also please check that the global OMVS AUTOCVT is set to OFF, or that its setting does not harm the processing of tagged files?  As far as I know, we do not tag any files for CCSID conversion during the install, but they may already have tags on exit from un-PAX.

**Comment by Joe-Winchester** [comment] 2019-09-16 16:35
@John-A-Davies - can we just export the variables without any path statements, and do this in just zowe-install.sh and zowe-configure.sh.  I don't believe we need to do anything in run-zowe.sh.  , i.e. just do
```
export _CEE_RUNOPTS=""
export _TAG_REDIR_IN=""
export _TAG_REDIR_OUT=""
export _TAG_REDIR_ERR=""
```

**Comment by John-A-Davies** [comment] 2019-09-17 08:38
We should also consider
```
export _BPXK_AUTOCVT="OFF"
```
depending on how we tag and convert our files.

**Comment by Joe-Winchester** [comment] 2019-09-23 10:52
This is fixed with zip-142 PR

**Closed by Joe-Winchester** 2019-09-23 10:52 UTC
Labels: Cupids, bug
