### ISSUE TITLE
Unable to deploy an extension using install-app.sh

### ISSUE THREAD

**Issue by kiril-ibm** [zowe/zowe-install-packaging#1182] opened 2020-03-05 19:41 UTC
10:37:57  Starting process 'command '/bin/sh''. Working directory: /opt/zowe/zowe-instance-dir/bin Command: /bin/sh -L -c /opt/zowe/zowe-instance-dir/bin/install-app.sh /opt/zowe/zowe-instance-dir/workspace/extensions/com.ibm.addi.web.mvd/addi-web-mvdapp
10:37:57  Successfully started process 'command '/bin/sh''
10:37:57  Verifying node exists
10:37:57  /opt/nodejs/node-v8.17.0-os390-s390x/bin/node is /opt/nodejs/node-v8.17.0-os390-s390x/bin/node
10:37:57  Running app-server plugin installer. Log=/opt/zowe/zowe-instance-dir/logs/install-app.log
10:37:57  utils_path=/opt/zowe/zowe-1.9.0//components/app-server/share/zlux-server-framework/utils
10:37:57  app_path=/opt/zowe/zowe-instance-dir/workspace/extensions/com.ibm.addi.web.mvd/addi-web-mvdapp
10:37:57  json_path=/opt/zowe/zowe-instance-dir/workspace/app-server/serverConfig/server.json
10:37:58  2020-03-05 15:37:58.768 <ZWED:83886095> IBMUSER INFO (_zsf.utils,util.js:284) ZWED0051I /opt/zowe/zowe-instance-dir/workspace/extensions/com.ibm.addi.web.mvd/addi-web-mvdapp /opt/zowe/zowe-instance-dir/workspace/extensions/com.ibm.addi.web.mvd/addi-web-mvdapp
10:37:58  2020-03-05 15:37:58.770 <ZWED:83886095> IBMUSER INFO (_zsf.utils,util.js:284) ZWED0051I /opt/zowe/zowe-instance-dir/workspace/app-server/serverConfig/server.json /opt/zowe/zowe-instance-dir/workspace/app-server/serverConfig/server.json
10:37:58  2020-03-05 15:37:58.771 <ZWED:83886095> IBMUSER INFO (_zsf.utils,util.js:284) ZWED0051I /opt/zowe/zowe-instance-dir/workspace/app-server/plugins /opt/zowe/zowe-instance-dir/workspace/app-server/plugins
10:37:58  2020-03-05 15:37:58.773  ZWED0109I - Registering App (ID=com.ibm.addi.web.mvd) with App Server
10:37:58  App extracted but not registered to App Server due to write fail. Error=EACCES: permission denied, open '/opt/zowe/zowe-instance-dir/workspace/app-server/plugins/com.ibm.addi.web.mvd.json'

I see that /opt/zowe/zowe-instance-dir/workspace/app-server/plugins/ is not writable by ZWEADMIN

**Comment by 1000TurquoisePogs** [comment] 2020-03-06 00:16
Is this a duplicate of https://github.com/zowe/zowe-install-packaging/issues/1141 or has something changed?

**Comment by kiril-ibm** [comment] 2020-03-06 02:23
It is new, another directory is affected

**Comment by kiril-ibm** [comment] 2020-03-06 16:41
@1000TurquoisePogs This time group is correct but group write permissions are not set

**Comment by kiril-ibm** [comment] 2020-03-06 17:04
One more not writable directory if we move fartrher
tee: FSUM7853 creating file "/opt/zowe/zowe-instance-dir/logs/install-app.log": EDC5111I Permission denied.

**Comment by 1000TurquoisePogs** [comment] 2020-03-06 18:30
It might be for the same reason as before: if you run `umask` is your umask 0022? It needs to be 0002 or similar in order for files & folders to be created with write permission. `umask -S` explains the number.
Maybe the code should ignore umask if this is likely to happen.

**Comment by 1000TurquoisePogs** [comment] 2020-03-09 18:56
This might fix it the plugin installation https://github.com/zowe/zlux-app-server/pull/105 but it won't fix the logs since that is controlled by `umask`

**Closed** 2022-12-05 20:28 UTC
