### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by wjs4572** [zowe/zowe-install-packaging#425] opened 2019-04-01 14:29 UTC
Our System Administrator and I have been working to install Zowe on our system and have been noticing several performance issues.  It appears that whenever any USS based process runs that requires the cryptographic services, that process will tie up the CPU.  Even high priority processes are not being responded to.  

This occurs for something as simply as running the Java keytool, or trying to run the started task for Zowe.  We have tried running both the Java 7 and Java 8 copies of the keytool command and both show this performance issue.  We also notice some performance issues related to z/OSMF.  This is a emulated system, ZPDT, so could this be something unique to the emulator?

Does anyone have any idea why this would be occurring, is there a configuration issue that we have overlooked?

**Comment by likepunk** [comment] 2019-04-01 16:21
Can you provide some more details(logs/messages) ?

I  have noticed z/OSMF can threshing the CPU(running 99%) for some reason - for example  
loading ‘IzuManagementFacilitySysplexManagement’ took 8500 seconds....

we had to add RESOLVER TRACE turned on when z/OSMF took forever to come up.( in //SYSTCPD DDCard)..and the above plugin loaded in 10 seconds!

We also noticed ZOWESVR takes lots of resources when starts especially for starting plugins as well.

I don't have zPDT but running them on 20965 with Z02 - would be good to collect performance metrics and their environmental configs to understand optimal settings.

**Comment by wjs4572** [comment] 2019-04-02 13:36
Looking through the log as, I do not want to post the whole thing here.  I suspect the delay is due to the following errors:

Error: Plugin org.zowe.zlux.auth.zosmf invalid  
Error: Plugin org.zowe.zlux.auth.trivial invalid 

privilegedServerName is not specified, or is NULL. 

For plugin=org.zowe.zlux.sample.react, found 0 data service(s)    
MALLOC failed, got NULL for size 0 at site DataServices           

com.sun.jersey.api.client.ClientHandlerException -> java.net.SocketTimeoutException: Read timed out  

ERROR 16843168 --- [_JRCV.JRC.LAN-0] c.n.e.cluster.ReplicationTaskProcessor   : It seems to be a socket read timeout exception retry later. if it continues to happen and some eureka node occupied all the cpu time, you should set property 'eureka.server.peer-node-read-timeout-ms' to a bigger value 

It looks like we may be missing some more RACF setttings to start, but whatever guidance you could provide would be appreciated.

Thank you,

**Comment by wjs4572** [comment] 2019-04-05 18:23
After examining the log further, we have identified an error that repeated 1800+ times before we killed the process.  Any idea what is causing this?

019-03-29 19:47:10.101 ERROR 16843168 --- [server_name-18] c.n.e.cluster.ReplicationTaskProcessor   : It seems to be a socket read timeout exception, it will retry later. if it continues to happen and s

com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out
    at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187) ~[jersey-apache-client4-1.19.1.jar!/:1.19.1]
    at com.netflix.eureka.cluster.DynamicGZIPContentEncodingFilter.handle(DynamicGZIPContentEncodingFilter.java:48) ~[eureka-core-1.9.3.jar!/:1.9.3]
    at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27) ~[eureka-client-1.9.3.jar!/:1.9.3]
    at com.sun.jersey.api.client.Client.handle(Client.java:652) ~[jersey-client-1.19.1.jar!/:1.19.1]
    at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682) ~[jersey-client-1.19.1.jar!/:1.19.1]
    at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74) ~[jersey-client-1.19.1.jar!/:1.19.1]
    at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570) ~[jersey-client-1.19.1.jar!/:1.19.1]
    at com.netflix.eureka.transport.JerseyReplicationClient.submitBatchUpdates(JerseyReplicationClient.java:116) ~[eureka-core-1.9.3.jar!/:1.9.3]
    at com.netflix.eureka.cluster.ReplicationTaskProcessor.process(ReplicationTaskProcessor.java:80) ~[eureka-core-1.9.3.jar!/:1.9.3]
    at com.netflix.eureka.util.batcher.TaskExecutors$BatchWorkerRunnable.run(TaskExecutors.java:187) [eureka-core-1.9.3.jar!/:1.9.3]
    at java.lang.Thread.run(Thread.java:812) [na:2.9 (09-15-2018)]
Caused by: java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:127) ~[na:1.8.0]
    at java.net.SocketInputStream.read(SocketInputStream.java:182) ~[na:1.8.0]
    at java.net.SocketInputStream.read(SocketInputStream.java:152) ~[na:1.8.0]
    at com.ibm.jsse2.b.a(b.java:228) ~[na:8.0 build_20180305]
    at com.ibm.jsse2.b.a(b.java:58) ~[na:8.0 build_20180305]
    at com.ibm.jsse2.av.a(av.java:562) ~[na:8.0 build_20180305]
    at com.ibm.jsse2.av.i(av.java:869) ~[na:8.0 build_20180305]
    at com.ibm.jsse2.av.a(av.java:19) ~[na:8.0 build_20180305]
    at com.ibm.jsse2.av.startHandshake(av.java:672) ~[na:8.0 build_20180305]
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396) ~[httpclient-4.5.6.jar!/:4.5.6]
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355) ~[httpclient-4.5.6.jar!/:4.5.6]
    at com.netflix.discovery.shared.transport.jersey.SSLSocketFactoryAdapter.connectSocket(SSLSocketFactoryAdapter.java:59) ~[eureka-client-1.9.3.jar!/:1.9.3]
    at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:414) ~[httpclient-4.5.6.jar!/:4.5.6]
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180) ~[httpclient-4.5.6.jar!/:4.5.6]
    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144) ~[httpclient-4.5.6.jar!/:4.5.6]
    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134) ~[httpclient-4.5.6.jar!/:4.5.6]
    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610) ~[httpclient-4.5.6.jar!/:4.5.6]
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445) ~[httpclient-4.5.6.jar!/:4.5.6]
    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~[httpclient-4.5.6.jar!/:4.5.6]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118) ~[httpclient-4.5.6.jar!/:4.5.6]
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.6.jar!/:4.5.6]
    at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173) ~[jersey-apache-client4-1.19.1.jar!/:1.19.1]
    ... 10 common frames omitted

**Comment by yugeshpothuru** [comment] 2019-06-28 13:29
hi,
I'm trying to install ZOWE on a zPDT system and struck with not being able to connect to the 
https://<appservername_port>/ZLUX/plugins/org.zowe.zlux.bootstrap/web/index.html

I have not even got the message 
[20xx-xx-xx xx:xx:xx.xxx _zsf.apiml INFO] - Eureka Client Registered

i see the below errors:
Problem making eureka request { Error: connect ECONNREFUSED 10.242.55.48:10011  
    at Object.exports._errnoException (util.js:1020:11)                         
    at exports._exceptionWithHostPort (util.js:1043:20)                         
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)             
  code: 'ECONNREFUSED',                                                         
  errno: 'ECONNREFUSED',                                                        
  syscall: 'connect',                                                           
  address: '10.242.55.48',                                                      
  port: 10011 }                                                                 

any help to resolve this issue is much appreciated.

**Comment by Joe-Winchester** [comment] 2019-11-14 17:13
Closing this issue as it is a duplicate of https://github.com/zowe/api-layer/issues/282 that has been fixed.  Please let me know if the problem still occurs with new Zowe builds and re-open the issue if that's the case.  Tks

**Closed by Joe-Winchester** 2019-11-14 17:13 UTC
