### ISSUE TITLE
dsName=PROCLIB may fail to copy proc to the target PROCLIB

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#574] opened 2019-07-26 17:14 UTC
Issue description:

In Marist college system, I found if I leave the `dsName=auto` as-is in the config yaml, the install is successful and the jcl will be put into `VENDOR.PROCLIB`. But if I change the config to `dsName=VENDOR.PROCLIB`, the install will fail at the copying proclib:

```
Attempting to create ZOWESVR PROCLIB member ...
Zowe 1.4.0 runtime install completed into directory /ZOWE/staging/zowe
The install script zowe-install.sh does not need to be re-run as it completed successfully
.....
Unable to create the PROCLIB member 
  Failed to put ZOWESVR.JCL in a PROCLIB dataset.
  Please add it manually from /ZOWE/staging/zowe/ZOWESVR.JCL to your PROCLIB
    To find PROCLIB datasets, issue /$D PROCLIB in SDSF
```

Below is `zowe-copy-proc.sh` log with `dsName=auto` which is successful:

```
<zowe-copy-proc.sh>
LOGNAME=ZOWEAD3
USER=ZOWEAD3
MAIL=/usr/mail/ZOWEAD3
HOME=/u/zowead3
whoami=ZOWEAD3
logname=ZOWEAD3
userid obtained from LISTUSER is ZOWEAD3
userid=[ZOWEAD3]
Old dataset ZOWEAD3.zowetemp.clist did not exist
Member name ZOWESVR was specified
Member name ZOWESVR was used
'auto' was requested: choose PROCLIB dataset automatically
Try JES2 PROCLIB concatenation
  procs = VENDOR.PROCLIB SVTSC.PROCLIB LVL0.PROCLIB SYS1.PROCLIB VENDOR.PROCLIB SVTSC.PROCLIB LVL0.PROCLIB SYS1.PROCLIB
  proclib = VENDOR.PROCLIB
  PROC ZOWESVR placed in VENDOR.PROCLIB 
</zowe-copy-proc.sh>
```

This is log with `dsName=VENDOR.PROCLIB`:

```
<zowe-copy-proc.sh>
LOGNAME=ZOWEAD3
USER=ZOWEAD3
MAIL=/usr/mail/ZOWEAD3
HOME=/u/zowead3
whoami=ZOWEAD3
logname=ZOWEAD3
userid obtained from LISTUSER is ZOWEAD3
userid=[ZOWEAD3]
Old dataset ZOWEAD3.zowetemp.clist did not exist
Member name ZOWESVR was specified
Member name ZOWESVR was used
PROCLIB dataset 'VENDOR.PROCLIB' was specified
    found PROCLIB dataset VENDOR.PROCLIB
  Unable to write to requested PROCLIB VENDOR.PROCLIB
Unable to create the PROCLIB member 
</zowe-copy-proc.sh>
```

**Comment by John-A-Davies** [comment] 2019-07-29 09:52
Closing as duplicate of #575.  I did not see this defect when I raised #575.

**Closed by John-A-Davies** 2019-07-29 09:52 UTC
