### ISSUE TITLE
zowe-configure-runtime.sh omits ZOWESVR member name from command

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zowe-install-packaging#979] opened 2020-01-15 16:22 UTC
**Describe the bug**
The messages issued by zowe-configure-runtime.sh instructing the user to START/STOP Zowe with SDSF commands omit the ZOWESVR PROCLIB member name which should come after the "/S " and "/C " commands

**To Reproduce**
Run zowe-configure-runtime.sh

**Comment by stevenhorsman** [comment] 2020-01-15 17:16
Assuming you mean zowe-configure-instance.sh - the echo has the PROCLIB MEMBER argument in it, but the problem is that the user hasn't defined it if they have changed it yet. If we hardcode that to ZWESVSTC (which I believe is the default) would that satisfy the requirement? or would you prefer if we described it eg `/S <ZOWE_SERVER_PROCLIB_MEMBER>,INSTANCE='<INSTANCE_DIR>`?

**Comment by stevenhorsman** [comment] 2020-01-21 10:24
Addressed by #987

**Closed** 2020-01-23 12:56 UTC
Labels: Cupids
