### ISSUE TITLE
zowe-install-packaging to create PTF user mods available in artifactory

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#876] opened 2019-11-25 15:25 UTC

**Comment by OnnoVdT** [comment] 2019-12-31 04:43
Is duplicate of https://github.com/zowe/zowe-install-packaging/issues/738 and https://github.com/zowe/zowe-install-packaging/issues/759 combined with https://github.com/zowe/zowe-install-packaging/issues/889

**Closed by OnnoVdT** 2019-12-31 04:43 UTC
