### ISSUE TITLE
Enable new component without restarting full Zowe

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2871] opened 2022-05-13 15:46 UTC
*Customer content*

**Is your feature request related to a problem? Please describe.**

If Zowe is already up and running and user installed new component, or enabled a component which wasn't enabled when Zowe is starting, this component will not be able to started with F modify command.

**Describe the solution you'd like**

- Allow the component to be initialized with validate and configure lifecycles, so the environment can be prepared before start.

**This definitely may cause potential inconsistency among already running components, the user should be aware of what he is trying to do and the potential consequences.

**Comment by 1000TurquoisePogs** [comment] 2024-06-27 13:46
Closing as duplicate of https://github.com/zowe/zowe-install-packaging/issues/3404

**Closed as completed by 1000TurquoisePogs** 2024-06-27 13:46 UTC
Labels: scrum discussion
